# Generated by Django 2.2.5 on 2020-12-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='web_db',
            table='users_two',
        ),
    ]
