# Generated by Django 2.2.5 on 2020-12-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201210_1634'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='web_db',
            table='users',
        ),
    ]
