# Generated by Django 2.2.5 on 2020-12-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='web_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.BooleanField(default=False)),
                ('age', models.IntegerField(default=18)),
                ('tel', models.CharField(max_length=11, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
